MIN_SIZE = (600, 400)
TITLE_BAR_HEIGHT = 40
APP_MAIN_COLOR = "#288278"
APP_MAIN_COLOR_DARK = "#216B6B"
APP_BG_COLOR = "#F9F9F9"
APP_BG_COLOR_DARK = "#E8E8E8"

STATUS_OFFLINE = 0
STATUS_ONLINE = 1
STATUS_BUSY = 2
STATUS_AWAY = 3
STATUS_INVISIBLE = 4

STATUS_STRING = ["offline", "online", "busy", "away", "invisible"]